### PR TITLE
Add basic spec for recipes and LICENSE

### LINKED ISSUE #6: Add basic spec for recipes
Would be nice to have some very basic spec for recipes in this repo:

something like:

```cr
describe "Compile available recipes" do
  it "compiles react recipe" do
    `amber new app -r react --deps`
    system("cd app && shards builld app").should be_true
  end
 
  # TODO: Add test for all recipes...
end
```

This will ensure us the recipes code isn't broken

We can use docker image for amber :point_right: https://hub.docker.com/r/amberframework/amber/

### PR DESCRIPTION
**Pull request by faustinoaq**
Fixes #6 

I commented `misc/modular` recipe spec because seems this recipe code is broken, see: #7 

Depends on #7 and #9

### CODE REVIEW

**Comment by damianham** [comment]
If you merge #5 or #9 then you can uncomment the modular spec
also I think you can simplify it by using shards build amber, e.g.
```
def build_amber
  unless File.exists?("./bin/amber")
    system("shards build amber")
  end
end

def generate_app(recipe)
  system("./bin/amber new app -r #{recipe} --deps")
end
```

**Comment by faustinoaq** [comment]
@damianham I just realize this spec is not checking PR changes, just master, because `-r <recipe>` will fetch always the master source.

I think we can modify the `recipe_source` on `.amber.yml`, WDYT?

**Comment by faustinoaq** [comment]
@damianham Done! :tada:

I just discover some issues with crecto scaffolding, I think this can be fixed later, I added a `TODO` comment

BTW, Can you approve #9 ?

**Comment by faustinoaq** [comment]
@damianham I added amber as dependency as you suggested, Is easier to use now :tada:

**Comment by faustinoaq** [comment]
@damianham Done! :tada: We still need to fix crecto scaffolding, though

**Comment by faustinoaq** [comment]
@damianham I gonna merge this, I already opened #10 to track the crecto issue

To merge master on your branches you can use `git merge master`

**Comment by faustinoaq** [comment]
@damianham I just realize this spec are affected by https://github.com/amberframework/micrate/issues/31 as well :sweat_smile:

**Pull request merged**
