### PR TITLE
Fix modular recipe

### LINKED ISSUE #8: Modular recipe is broken
When I use `amber new app -r misc/modular --deps && cd app && shards build app` I get this:

```
Error in src/app.cr:1: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:10: while requiring "../src/modules/**": can't find file '../src/modules/**' relative to '/home/main/Projects/recipes/app/config'

require "../src/modules/**"
^
```

This issue should be fixed because is required by #7

### PR DESCRIPTION
**Pull request by faustinoaq**
Fixes #8 

Required by #6

### CODE REVIEW

**Comment by faustinoaq** [comment]
This spec won't pass because `.travis.yml` is not available here yet, see #7

**Comment by damianham** [comment]
identical changes to #5 so this can be merged and delete #5 or vice versa

**Comment by faustinoaq** [comment]
@damianham I guess #5 doesn't update the `.zip` file, so I think we can merge this to get `crystal spec` working and then update #5 and include the `modular.zip` file with the updated js bundle.

**Comment by damianham** [comment]
@faustinoaq OK sounds like a good plan

**Pull request merged**
