### PR TITLE
Reorganisation of the recipes repo

### PR DESCRIPTION
**Pull request by damianham**
DO NOT MERGE SUPERCEDED BY #3 

Reorganise the recipes repo into theme folders with the recipes stored as code

### CODE REVIEW

**Comment by faustinoaq** [comment]
@eliasjpr recipes need to be downloaded, I think we should keep recipes optional, actually

IMO The default `app` should keep stored in `amberframework/amber` and used via `amber new app`

**Comment by damianham** [comment]
@eliasjpr yeah I wasn't sure what to call that folder - either default or basic.  I have a modular recipe in there as well which isn't really a default recipe so I called it basic.  Maybe the default recipe should live in the root then we can rename the basic folder to something else, e.g **misc** for a collection of recipes that don't fit one of the themes.  You ask the question about defaulting to the default recipe when none provided so that we can remove the default template from the amber CLI.  I don't think it is such a bad idea to remove the default template from amber and use the default recipe.  Faustino makes a good point that recipes need to be downloaded...... but we are building webapps anyway and the user needs to be online to get started so it is an online world.  Once any recipe is downloaded it is cached so available locally offline for future use also.   Overall it is a fairly simple code change to use the default recipe when none given.  I suppose it will not impact the test suite in any way?

**Comment by faustinoaq** [comment]
@damianham Oh!, you're right!, recipes are cached!, so, I think we should go ahead and move the [`cli/templates/app`](https://github.com/amberframework/amber/tree/master/src/amber/cli/templates/app) folder to this repo :+1:

**Comment by damianham** [comment]
Guys please take a look at the comments on https://github.com/amberframework/amber/pull/766 Add Jennifer support.  My suggestion is to add support for jennifer and any other ORM for that matter with recipes.  My initial thoughts were that the recipe templates would become unwieldy in order to support many different ORMs.  This also touches on the suggestion to remove the default template from the amber core and instead use a default recipe.  I think we can simplify the default recipes removing conditional sections from the templates and instead have recipes for each ORM.  There is one drawback in that we will have more recipes to maintain however by using a recipe by default based on the given options we could support any ORM without any modification to the amber core codebase.  We also might find in the future a need to differentiate between database and template language so at some time in the future we could use a template for each combination of options.

Given the above - I am in favour of closing this PR without merging and I will issue a new PR which only contains the reorganisation based on a default recipe per ORM and the preact recipe in an independent PR (which it should have been anyway :grin: )

**Comment by faustinoaq** [comment]
Wow, this is a huge PR, I will take some time to read it entirely

@damianham Thank you for your awesome work! :sparkles: :grinning:

**Comment by damianham** [comment]
@faustinoaq Please ignore this PR, it has been superceded by #3  - I left it here without closing it for historical context.

**Pull request closed without merging**
