### PR TITLE
updated shard.yml to match amber 0.7.2 template

### PR DESCRIPTION
**Pull request by damianham**
updated modular/app/shard.yml to match amber latest

### CODE REVIEW

**Comment by robacarp** [comment]
Perhaps I misunderstood when this all started, but what's the point of storing zip files in a version control system?

**Comment by damianham** [comment]
Well it was a choice when downloading a template, and downloading and extracting a zip file seemed the easiest choice rather than trying to copy a subtree from github.  Hence the recipe templates are stored in zip files.

**Comment by faustinoaq** [comment]
I'm working on new the new `amber watch` (configurable) and new exception pages, I guess the recipes will need a bit of refactoring after that :sweat_smile: 

amber v0.8.0 gonna be a bit different, with new features and enhancements :wink:

**Comment by damianham** [comment]
@faustinoaq I don't think we need to test the zip files if the recipe source is being tested but I agree we can rebuild the zip file for a recipe if the recipe passes the test suite.  Once we are auto rebuilding the zip files we can add the dist folder to .gitignore

**Comment by faustinoaq** [comment]
@damianham Yeah, auto rebuilding the zip files seems the right way, although I don't have idea how to do it :sweat_smile: Maybe using some github hook?

**Comment by damianham** [comment]
I am going to close this without merging as I think it is out of date already.  The zips have been updated by other PRs

**Comment by faustinoaq** [comment]
> We can always rebuild the zips in the travis build for each recipe that passes the test suite and then publish the rebuilt zips somewhere, for example publishing to S3 would be straight forward.

@damianham We are already being sponsored by Digital Ocean, maybe we can use their new [spaces feature](https://www.digitalocean.com/products/spaces/) for this, @amberframework/core-team WDYT?

**Comment by damianham** [comment]
@faustinoaq storing the zip files for distribution in DO rather than the repo would be a good idea.  Can you get a spaces feature setup so we can push the zip files to it ?  You might need to add access keys as environment variables in the travis build.

**Comment by faustinoaq** [comment]
@damianham Yeah, DO spaces seems a good I thing, although, we need to discuss a bit more about that. I don't know if DO sponsoring covers spaces feature as well :sweat_smile:

**Pull request closed without merging**
